api_platform:
    title: BookMarket API
    description: API for BookMarket application
    version: 1.0.0
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Dto'
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

